project:
  render:
    - index.qmd
  output-dir: ../public
  pre-render: ../setup.sh

format:
  revealjs:
    favicon: ../tvboptim.ico

website:
  favicon: ../tvboptim.ico

jupyter: python3

execute:
  freeze: auto

cache: true