---
title: Brain Simulation 3.0
subtitle: Introducing simple, fast, and reproducible workflows with `TVB-O` & `TVB-Optim`

format:
  clean-revealjs:
    width: 1244
    height: 750
    toc-font-size: 1.5em
    css: style.css
    cap-location: top
    footer: "© Marius Pille, Leon Martin, Petra Ritter, Charité University Medicine Berlin"
    code-overflow: wrap
    preview-links: false
    self-contained: true
    include-in-header:
      - header.html
    template-partials:
      - title-slide.html
    margin: 0.05
    mermaid-format: html
    mermaid:
      theme: neutral
    embed-resources: true
    preload-iframes: true
    default-image-extension: svg

author:
  - name: Marius Pille
    orcid: 0009-0000-5087-8450
    email: marius.pille@bih-charite.de
    affiliations: Berlin Institute of Health at Charité University Medicine
  - name: Leon Martin
    orcid: 0000-0002-2599-0165
    email: leon.martin@bih-charite.de
    affiliations: Berlin Institute of Health at Charité University Medicine
date: last-modified
bibliography: bibliography.bib
---
## Motivation

- What is wrong with TVB?
- Can we do better?

## Classic TVB - History

::: {.incremental}
* Python code base - first commit on GitHib 12th Feb 2015 - in that time:
  - Python 2.7 was still the standard
  - Python packaging was still a mess (pip only just got bundled with python + setup.py)
  - Machine Learning meant gradient boosted trees & CNNs for vision
:::

## Classic TVB - Math

$$
\begin{align*}
dS_i &= \left[f_d(S_i, \theta^d, C_i, I_i) \right]dt + g(S_i, \theta^g)\, dW_i \\
C_i &= f_c^{\text{post}}\Big(\sum_j A_{ij}\, f_c^{\text{pre}}(S_i, S_j(t-\tau_{ij}), \theta^c), S_i, \theta^c\Big)
\end{align*} \\
$$

::: {style="font-size: 0.55em;"}

**State Evolution**

- $S_i$ - state variables at node $i$
- $f_d$ - dynamics function with parameters $\theta^d$
- $C_i$ - coupling input from connected nodes
- $I_i$ - external input (stimulation, driving signals)
- $g$ - noise diffusion coefficient with parameters $\theta^g$
- $dW_i$ - Wiener process (stochastic fluctuations)

**Coupling**

- $f_c^{\text{pre}}$ - pre-aggregation transformation
- $A_{ij}$ - structural connectivity weight ($j \to i$)
- $\tau_{ij}$ - transmission delay (tract length / conduction speed)
- $f_c^{\text{post}}$ - post-aggregation transformation
- $\theta^c$ - coupling parameters

:::


## Specify Reproducible Simulation Experiments with:


![Knowledge Management for Digital Brain Twins [@Martin2025]](figures/tvbo_logo.png)

## Basic Ideas and Concepts

* separation model specification from code implementation (PDF for brain simulation)
* One specification - multiple backends



## What's New
- Discrete Models
- PDEs
- New Backends
  - Jax
  - tvboptim
  - pyrates
  - julia
  - cuda
  - neuroML
  - neuroblox?
  - tvb-cpp?
  - jaxley?

## Node Dynamics {auto-animate=true}


:::: {.columns}

::: {.column width="50%"}
```yaml
name: PendulumSystem
parameters:
    c:
        value: 0.001
        unit: 1/ms
    omega0:
        value: 0.01
        unit: rad/ms
    L:
        value: 1.0
        unit: m

state_variables:
    theta:
        unit: rad
        initial_value: 1.0
        equation:
            rhs: omega
    omega:
        unit: rad/ms
        initial_value: 0.0
        equation:
            rhs: -c*omega - omega0**2 * sin(theta)
```
:::
::: {.column width="50%"}

```python
from tvbo import Dynamics
pendulum = Dynamics.from_string(dynamics_yaml)
pendulum.render('report')
```

#### PendulumSystem


##### State Equations
$$
\dot{\theta} = \omega
$$
$$
\dot{\omega} = - c*\omega - \omega_{0}^{2}*\sin{\left(\theta \right)}
$$

##### Parameters

| **Parameter** | **Value** | **Unit** | **Description** |
|---------------|-----------|----------|-----------------|
| $c$ | 0.001 | $\mathrm{ms}^{-1}$ | None |
| $\omega_{0}$ | 0.01 | $\frac{\mathrm{rad}}{\mathrm{ms}}$ | None |
| $L$ | 1.0 | $\mathrm{m}$ | None |

:::

::::


<!-- {{< include Slides/tvbo.qmd >}} -->

<!-- {{< include Slides/tvbo-jansen1995-replication.qmd >}} -->

## Run and Optimize models with:

![A JAX-based framework for brain network simulation and gradient-based optimization [@Pille2025].](figures/tvboptim.png)

<!-- {{< include Slides/tvboptim.qmd >}} -->

## Biological Mechanistic Model-Discovery

## Hands-On

* Link:

## References